kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: elasticsearch
  namespace: af2668-tools
  uid: 4ae22568-aa8c-4a57-a395-1bb6622aa02a
  resourceVersion: '2907772605'
  creationTimestamp: '2022-03-01T00:35:09Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: template.openshift.io/v1
      time: '2022-03-01T00:35:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:labels':
          .: {}
          'f:app': {}
          'f:build': {}
          'f:template': {}
        'f:objects': {}
        'f:parameters': {}
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}'
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: '${NAME}'
      labels:
        buildconfig: '${NAME}'
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}:${ES_VERSION}'
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      successfulBuildsHistoryLimit: 3
      failedBuildsHistoryLimit: 3
      completionDeadlineSeconds: 600
      strategy:
        dockerStrategy:
          buildArgs:
            - name: ES_VERSION
              value: '${ES_VERSION}'
          from:
            kind: DockerImage
            name: 'docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}'
        type: Docker
      postCommit: {}
      source:
        dockerfile: >
          FROM BuildConfig

          ARG ES_VERSION

          ENV ES_PWD=test

          ENV TZ=America/Vancouver

          COPY ./elastic-certificate/elastic-certificate.b64 /usr/share/elasticsearch/config/elastic-certificate.b64

          RUN base64 -d /usr/share/elasticsearch/config/elastic-certificate.b64
          > /usr/share/elasticsearch/config/elastic-certificates.p12 && \
              chmod 644 /usr/share/elasticsearch/config/elastic-certificates.p12 && \
              rm /usr/share/elasticsearch/config/elastic-certificates.b64 && \
              cd /usr/share/elasticsearch/bin && \
              echo ${ES_PWD} | elasticsearch-keystore add "bootstrap.password" -f
        type: Dockerfile
        configMaps:
          - configMap:
              name: elastic-certificate
            destinationDir: elastic-certificate
      triggers:
        - type: ConfigChange
      runPolicy: SerialLatestOnly
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    value: elasticsearch
    required: true
  - name: ES_VERSION
    displayName: ES Version
    description: Version of ElasticSearch to use
    value: 8.0.0
    required: true
  - name: ES_PWD
    displayName: Elastic Password
    description: Initial elastic password
    generate: expression
    from: '[a-zA-Z0-9]{16}'
    required: true
labels:
  app: elasticsearch
  build: '${NAME}'
  template: '${NAME}-bc-template'
